正如名字一样，这个(recover)内建函数被用于从panic或错误场景中恢复：让程序可以从panicking
重新获得控制权，停止终止过程进而恢复正常执行。

recover只能在defer修饰的函数中使用：用于取得panic调用中传递过来的错误值，如果是正常执行，
调用recover不会有任何效果，返回nil。

总结：panic会导致栈被展开直到defer修饰的recover()被调用或者程序中止。


